name: bicycle

on:
  push:
    branches:
      - main

jobs:
  karanDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: git library
        uses: actions/checkout@v4
      - name: connection
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{secrets.IP}}
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

          script: |
            cd /home/karan/frontendBicycle
            git pull origin main
            sudo npm i
            sudo npm run build
            cd dist/bicycle/
            pm2 delete "from git"
            pm2 start --name "from git" http-server -- -p 4200 -d false
            
            
            
        
